version: "2.4"

services:

  operator:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-operator:${VERSION:-latest}
    build:
      context: .
    environment:
      ENGINE_TYPE: Web3.Operator.Engines.DockerEngine.DockerEngineOperator, DockerEngineOperator
      ENGINE_URL: npipe://./pipe/docker_engine
      Operator__HostNamePattern: '{0}-127-0-0-1.nip.io'
      Operator__InstanceImage: sitecore-glitterfish-cm:latest
      Operator__DefaultMemoryMb: 1500
      Operator__DockerNetworkName: ${NETWORK_NAME}
    networks:
      - net
    volumes:
    - type: npipe
      source: \\.\pipe\docker_engine
      target: \\.\pipe\docker_engine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.operator.entrypoints=web"
      - "traefik.http.routers.operator.rule=Host(`operator-127-0-0-1.nip.io`)"

  traefik:
    image: traefik:v2.6.1-windowsservercore-1809
    command:
      - "--ping"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
    ports:
      - "80:80"
      - "8079:8080"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    networks:
      - net
    volumes:
      - source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
        type: npipe

networks:
  net:
    external:
      name: ${NETWORK_NAME}